version: '3.4'

services:
  postgres:
    container_name: "postgresql"
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "PGDATA=/var/lib/postgresql/data/pgdata"

  my-app-db-admin:
    container_name: "my-app-db-admin"
    image: dpage/pgadmin4
    ports:
      - "5480:80"
    expose:
      - "80"
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=dnckd18@nate.com"
      - "PGADMIN_DEFAULT_PASSWORD=1234"